### ISSUE TITLE
Writing docs using NaturalDocs

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#13]
We should properly document our code files. I think we should use [NaturalDocs](http://www.naturaldocs.org/) as it supports multiple languages, meaning we don't have to use different documentation systems for Python and JS

**Comment by Gelo147** [comment]
Sure, I'll have to remember to do it but sure, also will try to finish that reset today.

**Comment by freyamade** [comment]
I'm documenting all the stuff we've already written, trying to get natural docs to work

**Comment by Gelo147** [comment]
Perfect, on a side note, did you know CUH has better eduroam connection then UCC?

**Comment by freyamade** [comment]
I've written the server.py docs, and they are in the docs folder in the `docs_testing` branch. Will you check them for me and let me know what you think

Create a branch for it, pull the docs_testing branch and open the index.html in a browser

**Comment by Gelo147** [comment]
Looking at it now

**Comment by Gelo147** [comment]
Looks good

**Comment by freyamade** [comment]
Right, I'm working on arena.js now

**Comment by freyamade** [comment]
Finished arena.js if you want to look at it

**Comment by freyamade** [comment]
This was supposed to close automatically when the request was merged but clearly not
