### ISSUE TITLE
Inform the server when a player leaves the game

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#18]
Going out of the lobby page, and then pressing back causes the server to throw an exception.

We need to inform the server that somebody has left the lobby

**Comment by freyamade** [comment]
Or left the game for that matter

**Comment by Gelo147** [comment]
A couple of notes:
- \- _Special Case_ Host leaves lobby
- -Player Leaves Lobby vs Player Leaves Ongoing Game

**Comment by freyamade** [comment]
Suggestion for you;  have a _time_since_last_request_ dict in the server. Have a thread checking this dict every second or something? And update the times whenever a player sends a request

Not 100% that this will work, looking up intervals in python as we speak

**Comment by freyamade** [comment]
http://stackoverflow.com/a/3393759

**Comment by freyamade** [comment]
Also try looking up the onbeforeunload event

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by freyamade** [comment]
Just to remind myself; edit lobby.js to allow only the host to click the button
