### ISSUE TITLE
Players able to 'double connect'

### ISSUE THREAD

**Issue by Gelo147** [ExceptionalVoid/Arena#20]
Onece a player has joined, if they go back to lobby and join again they are added as a new player.

**Comment by freyamade** [comment]
I think I already know how to fix this, I can take it if you want?

**Comment by freyamade** [comment]
Also have realised the presence of a minor issue, but since it's in the same file as this one I will solve them both in this branch

**Comment by freyamade** [comment]
Not actually fixed

**Comment by crnbrdrck** [comment]
In reality this wasn't even a big issue; the connection of the second player would have timed out the first xD

**Comment by freyamade** [comment]
This is still slightly buggy, but hopefully when we make the login part of it then it should be okay to leave it the way it is
