### ISSUE TITLE
Firefox isn't working

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#39]
Fix the cookies, that's the problem

**Comment by Gelo147** [comment]
Well... it is... nope it's not.. it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not...it is... it's not... 

Let's just assume it's not,
