### ISSUE TITLE
Netsoc CLI server

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#46]
Colm asked, and we'll deliver ;) ;) ;) ;) ;) ;) ;)

**Comment by freyamade** [comment]
Relies on #47

**Comment by freyamade** [comment]
I know you implemented this in #70 hero but I just realised that our implementation is a little lacking. We still need to log things into a file and other minor things

**Comment by hero24** [comment]
thats doable, once you list the other minor things
