### ISSUE TITLE
Automate Cross-Origin Allowance

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#47]
Right now, our Access-Control-Allow-Origin header is set to cs1.ucc.ie. we need to make this easily customisable, if we want to push this for a release.

**Comment by Gelo147** [comment]
Could we add an option for it in the server start up?? Like with the initial information exchange.

**Comment by freyamade** [comment]
I think that's doable yeah

**Comment by freyamade** [comment]
Maybe when join is called by the player who will become the host, we take the url it came from or something?

**Comment by freyamade** [comment]
I just learned we can use Access-Control-Allow-Origin: * to allow any origin. The question is, should we use it or is there too big a security risk?
