### ISSUE TITLE
Add multiple maps

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#50]
Maybe have a JSON file with different sets of obstacle coordinates and the server will pick one at random and send the filename to the JS

**Comment by hero24** [comment]
why at random?

**Comment by freyamade** [comment]
How do we allow selection of map for CLI though? We can add a dropdown in the gui but at best the cl will have to prompt all the available maps

**Comment by hero24** [comment]
hmm how about Arena -sam for show available maps and Arena -cm "Map name" for choose map ?
I can propose even better solution, how about allow host to choose a map from available maps through web browser?

**Comment by freyamade** [comment]
I like that last suggestion yeah
