### ISSUE TITLE
Obstacle Types

### ISSUE THREAD

**Issue by freyamade** [ExceptionalVoid/Arena#53]
Hero gave me an idea:

- Blue Obstacles
  - Bullets bounce, players pass through

- Green Obstacles
  - Opposite of blue

- Orange Obstacles
  - Nothing can pass through

- Red Obstacles
  - Hurt players and destroy bullets

Thoughts?

**Comment by freyamade** [comment]
Implemented in Arena: Electron

**Comment by hero24** [comment]
Great now its time to implement yellow and green :
Green - destroy bullets, do nothing to players :-)
Yellow - hurt players do nothing to bullets

**Comment by freyamade** [comment]
Maybe, we'll see

At least since we're using classes in the new version it's as easy as creating new subclasses
